version: '0.2'
phases:
  install:
    runtime-versions:
      php: '8.2'
    commands:
    - composer install --ignore-platform-req=ext-filter
  build:
    commands:
    - ./vendor/bin/phpunit
reports:
  test-report:
    files:
      - build/reports.xml
    file-format: JunitXml
